-- Migration for Third-Party Integrations and Advanced AI Features

-- Third-Party Integration Settings
CREATE TABLE IF NOT EXISTS integration_settings (
    setting_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    integration_type ENUM('GOFOOD', 'GRABFOOD', 'SHOPEEFOOD', 'MAXIM', 'QRIS', 'WHATSAPP', 'PAYMENT_GATEWAY') NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    is_encrypted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (setting_id),
    UNIQUE KEY idx_integration_settings_tenant_type_key (tenant_id, branch_id, integration_type, setting_key),
    KEY idx_integration_settings_tenant_id (tenant_id),
    KEY idx_integration_settings_type (integration_type),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS integration_logs (
    log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    integration_type ENUM('GOFOOD', 'GRABFOOD', 'SHOPEEFOOD', 'MAXIM', 'QRIS', 'WHATSAPP', 'PAYMENT_GATEWAY') NOT NULL,
    action VARCHAR(50) NOT NULL,
    request_payload TEXT,
    response_payload TEXT,
    status ENUM('SUCCESS', 'ERROR', 'PENDING') DEFAULT 'PENDING',
    error_message TEXT,
    external_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (log_id),
    KEY idx_integration_logs_tenant_id (tenant_id),
    KEY idx_integration_logs_type (integration_type),
    KEY idx_integration_logs_status (status),
    KEY idx_integration_logs_created (created_at),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Advanced AI Features Tables
CREATE TABLE IF NOT EXISTS ai_menu_engineering (
    analysis_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    analysis_date DATE NOT NULL,
    product_id BIGINT UNSIGNED,
    product_name VARCHAR(150),
    current_price DECIMAL(10,2),
    cost DECIMAL(10,2),
    margin DECIMAL(5,2),
    sales_volume INT,
    popularity_score DECIMAL(5,2),
    profit_score DECIMAL(5,2),
    menu_mix_score DECIMAL(5,2),
    recommendation ENUM('KEEP', 'REPRICE', 'PROMOTE', 'REMOVE', 'FEATURE'),
    recommended_price DECIMAL(10,2),
    reasoning TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (analysis_id),
    KEY idx_ai_menu_engineering_tenant_id (tenant_id),
    KEY idx_ai_menu_engineering_branch_id (branch_id),
    KEY idx_ai_menu_engineering_date (analysis_date),
    KEY idx_ai_menu_engineering_product (product_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_staff_optimization (
    optimization_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    date DATE NOT NULL,
    hour INT NOT NULL,
    predicted_orders INT,
    required_staff INT,
    current_staff INT,
    overstaffed BOOLEAN,
    understaffed BOOLEAN,
    cost_savings DECIMAL(10,2),
    recommendation TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (optimization_id),
    KEY idx_ai_staff_optimization_tenant_id (tenant_id),
    KEY idx_ai_staff_optimization_branch_id (branch_id),
    KEY idx_ai_staff_optimization_date (date),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_fraud_detection (
    alert_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    alert_type ENUM('UNUSUAL_ORDER', 'VOID_PATTERN', 'DISCOUNT_ABUSE', 'STOCK_THEFT', 'CASH_SHORTAGE', 'PRICE_MANIPULATION') NOT NULL,
    severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'),
    description TEXT,
    related_order_id BIGINT UNSIGNED,
    related_user_id BIGINT UNSIGNED,
    risk_score DECIMAL(5,2),
    status ENUM('NEW', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE') DEFAULT 'NEW',
    resolution_notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (alert_id),
    KEY idx_ai_fraud_detection_tenant_id (tenant_id),
    KEY idx_ai_fraud_detection_branch_id (branch_id),
    KEY idx_ai_fraud_detection_type (alert_type),
    KEY idx_ai_fraud_detection_status (status),
    KEY idx_ai_fraud_detection_created (created_at),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_executive_intelligence (
    insight_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    insight_category ENUM('FINANCIAL', 'OPERATIONAL', 'MARKETING', 'STRATEGIC') NOT NULL,
    insight_title VARCHAR(200),
    insight_description TEXT,
    metrics JSON,
    trend ENUM('IMPROVING', 'DECLINING', 'STABLE', 'VOLATILE'),
    impact_level ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'),
    recommended_actions TEXT,
    priority INT DEFAULT 0,
    status ENUM('NEW', 'REVIEWED', 'IMPLEMENTED', 'DISMISSED') DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (insight_id),
    KEY idx_ai_executive_intelligence_tenant_id (tenant_id),
    KEY idx_ai_executive_intelligence_branch_id (branch_id),
    KEY idx_ai_executive_intelligence_category (insight_category),
    KEY idx_ai_executive_intelligence_status (status),
    KEY idx_ai_executive_intelligence_priority (priority),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Enterprise Features Tables
CREATE TABLE IF NOT EXISTS shift_schedules (
    schedule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED NOT NULL,
    employee_id BIGINT UNSIGNED,
    shift_date DATE NOT NULL,
    shift_type ENUM('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT') NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status ENUM('SCHEDULED', 'ASSIGNED', 'COMPLETED', 'ABSENT') DEFAULT 'SCHEDULED',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (schedule_id),
    KEY idx_shift_schedules_tenant_id (tenant_id),
    KEY idx_shift_schedules_branch_id (branch_id),
    KEY idx_shift_schedules_employee_id (employee_id),
    KEY idx_shift_schedules_date (shift_date),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS performance_evaluations (
    evaluation_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    employee_id BIGINT UNSIGNED NOT NULL,
    evaluation_period_start DATE NOT NULL,
    evaluation_period_end DATE NOT NULL,
    overall_score DECIMAL(5,2),
    attendance_score DECIMAL(5,2),
    productivity_score DECIMAL(5,2),
    quality_score DECIMAL(5,2),
    customer_service_score DECIMAL(5,2),
    teamwork_score DECIMAL(5,2),
    comments TEXT,
    evaluator_id BIGINT UNSIGNED,
    status ENUM('DRAFT', 'SUBMITTED', 'APPROVED') DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (evaluation_id),
    KEY idx_performance_evaluations_tenant_id (tenant_id),
    KEY idx_performance_evaluations_branch_id (branch_id),
    KEY idx_performance_evaluations_employee_id (employee_id),
    KEY idx_performance_evaluations_period (evaluation_period_start, evaluation_period_end),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (evaluator_id) REFERENCES users(user_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cash_flow (
    cash_flow_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    flow_date DATE NOT NULL,
    flow_type ENUM('INFLOW', 'OUTFLOW') NOT NULL,
    category VARCHAR(100),
    amount DECIMAL(15,2),
    description TEXT,
    reference_type VARCHAR(50),
    reference_id BIGINT UNSIGNED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cash_flow_id),
    KEY idx_cash_flow_tenant_id (tenant_id),
    KEY idx_cash_flow_branch_id (branch_id),
    KEY idx_cash_flow_date (flow_date),
    KEY idx_cash_flow_type (flow_type),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS budgets (
    budget_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED,
    budget_name VARCHAR(150) NOT NULL,
    budget_type ENUM('REVENUE', 'EXPENSE', 'PROFIT') NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    budgeted_amount DECIMAL(15,2),
    actual_amount DECIMAL(15,2),
    variance DECIMAL(15,2),
    variance_percentage DECIMAL(5,2),
    status ENUM('ACTIVE', 'CLOSED') DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (budget_id),
    KEY idx_budgets_tenant_id (tenant_id),
    KEY idx_budgets_branch_id (branch_id),
    KEY idx_budgets_period (period_start, period_end),
    KEY idx_budgets_type (budget_type),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
